theme: minima

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-paginate
